import type { NextPage, GetStaticProps } from 'next';
import Head from 'next/head';
import classes from '../styles/Home.module.scss';
import { Navbar, Searchbar, Statistics, Blocks, Transactions } from '../components';
import {useState} from 'react';
import Router from 'next/router';
import { useRouter } from 'next/router';


const Home: NextPage = ({ infura, ethPrice, transactions, transBatch }: any) => {
  
  console.log('batch', transBatch);

  return (
    <div className={classes.container}>
      <Head>
        <title>Etherskan</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://i.icomoon.io/public/temp/4dd956f873/UntitledProject/style-svg.css" />
        <script defer src="https://i.icomoon.io/public/temp/4dd956f873/UntitledProject/svgxuse.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/@alch/alchemy-web3@latest/dist/alchemyWeb3.min.js"></script>
      </Head>
      <main className={classes.main}>
        <section className={classes.searchbarSection}>
          <Searchbar />
        </section>
        <section>
          <Statistics ethPrice={ethPrice} />
        </section>
        <section className={classes.blockTransactionSection}>
          <div className={classes.blocks}>
            <Blocks />
          </div>
          <div className={classes.transactions}>
            <Transactions transactions={transBatch} />
          </div>
        </section>
      </main>
    </div>
  )
}


export async function getStaticProps(context: any) {
  const { params } = context;
  const Web3 = require('web3');
  
  const { createAlchemyWeb3 } = require("@alch/alchemy-web3");
  const web3 = createAlchemyWeb3(`https://eth-rinkeby.alchemyapi.io/v2/${process.env.NEXT_PUBLIC_ALCHEMY_API_KEY}`);

  const [infuraRes, ethPriceRes, latestBlock] = await Promise.all([
    fetch(`https://rinkeby.infura.io/v3/${process.env.INFURA_PROJECT_ID}`, {
      body: '{"jsonrpc":"2.0","method":"eth_hashrate","params":[],"id":1}',
      headers: {
        "Content-Type": "application/json"
      },
      method: "POST"
    }),
    fetch("https://coinranking1.p.rapidapi.com/coin/razxDUgYGNAdQ?referenceCurrencyUuid=yhjMzLPhuIDl&timePeriod=24h", {
      "method": "GET",
      "headers": {
        "x-rapidapi-host": "coinranking1.p.rapidapi.com",
        "x-rapidapi-key": `${process.env.RAPID_API_KEY}`,
      }
    }),
    web3.eth.getBlock('latest'),
    
  ])

  const [infura, ethPrice, transactions ] = await Promise.all([
    infuraRes.json(),
    ethPriceRes.json(),
    latestBlock.transactions,
    
  ])

  let transBatch = [];
  for (let i=0; i< 10; i++) {
    let res = await web3.eth.getTransactionFromBlock(latestBlock.number, i);
    transBatch.push(res);
  }

  return {
    props: {
      infura,
      ethPrice,
      transactions,
      transBatch,
    }
  }
}

export default Home;
